# Generated by Django 4.0.5 on 2022-06-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.FileField(upload_to='E:\\django\\django_projects\\ecomerce\\images'),
        ),
    ]
