# Generated by Django 4.0.5 on 2022-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='homeimage',
            field=models.FileField(null=True, upload_to='E:\\django\\django_projects\\ecomerce\\images'),
        ),
    ]
