# Generated by Django 3.2.13 on 2022-06-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_homeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='homeimage',
            field=models.FileField(upload_to='./images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.FileField(upload_to='./images'),
        ),
    ]
