# Generated by Django 3.2.13 on 2022-06-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220616_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='homeimage',
            field=models.FileField(upload_to='./statics/images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.FileField(upload_to='./statics/imasges'),
        ),
    ]
