# Generated by Django 3.2.13 on 2022-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='', max_length=50),
        ),
    ]
