# Generated by Django 3.2.13 on 2022-06-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numberofrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.FileField(upload_to='./statics/images/categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(upload_to='./statics/images/products'),
        ),
    ]
