# Generated by Django 3.2.13 on 2022-06-28 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=80),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.TextField(max_length=70)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productRate', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userRate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
